'use strict';
const $=id=>document.getElementById(id), names={mean_fade:'MR',conditioned:'CO',pca_residual:'PCA'};
const fmt=(x,n=2)=>Number.isFinite(x)?x.toFixed(n):'—';
const pct=x=>Number.isFinite(x)?fmt(x*100,1)+'%':'—';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sg=x=>x?new Date(x).toLocaleString('en-GB',{timeZone:'Asia/Singapore',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})+' SGT':'—';
const day=x=>x?new Date(x).toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'}):'';
function trade(d,s){
 if(!s||![1,-1].includes(d))return {label:'—',detail:'',legs:[]};
 const forwards=s.name.match(/\d+y\d+y/g),spot=s.name.match(/\d+(?:s\d+)+/),tenors=forwards||spot?.[0].split('s').map(t=>t+'Y')||[];
 const weights=tenors.length===3?[-1,2,-1]:tenors.length===2?[-1,1]:[1];
 const legs=s.ccys.flatMap((ccy,i)=>tenors.map((tenor,j)=>({ccy,tenor,coefficient:d*(i===0?1:-1)*weights[j]})));
 const fly=tenors.length===3,cross=s.ccys.length===2,verb=d===1?'Pay':'Receive',opposite=d===1?'receive':'pay';
 let label;
 if(cross&&fly)label=`${verb} ${s.ccys[0]} / ${opposite} ${s.ccys[1]} belly`;
 else if(cross&&tenors.length===2)label=`${d===1?'Steepen':'Flatten'} ${s.ccys[0]} / ${d===1?'flatten':'steepen'} ${s.ccys[1]}`;
 else if(cross)label=`${verb} ${s.ccys[0]} / ${opposite} ${s.ccys[1]}`;
 else if(fly)label=`${verb} ${tenors[1]} belly`;
 else label=d===1?'Steepener':'Flattener';
 const describe=sign=>legs.filter(l=>Math.sign(l.coefficient)===sign).map(l=>(cross?l.ccy+' ':'')+l.tenor).join(' / ');
 return {label,detail:`Pay ${describe(1)} · Receive ${describe(-1)}`,legs};
}
const direction=(d,s=selected)=>esc(trade(d,s).label);
function directionCell(d,s){const t=trade(d,s);return `<span class="trade-direction">${esc(t.label)}</span><small class="trade-legs">${esc(t.detail)}</small>`}
function quoteCell(g){
 const readings=g.models.map(v=>{const c=modelValue(v.m)||{},current=v.m.current?.status==='current_cached_indication';return {model:v.m.model,value:c.quote_bp,date:current?'Cache '+sg(c.latest_snapshot_at||c.oldest_snapshot_at):'Close '+(c.date||index.cutoff)}});
 const same=readings.every(r=>(r.value===readings[0].value||Number.isFinite(r.value)&&Number.isFinite(readings[0].value)&&Math.abs(r.value-readings[0].value)<1e-8)&&r.date===readings[0].date);
 const render=r=>`<span class="quote-level">${fmt(r.value)}</span><small class="quote-date">${esc(r.date)}</small>`;
 return same?render(readings[0]):readings.map(r=>`<span class="model-line"><small>${names[r.model]}</small> ${render(r)}</span>`).join('');
}
const norm=x=>x.toLowerCase().replace(/eur\b/g,'estr').replace(/[^a-z0-9]/g,'');
let index, selected, selectedModel, requestNumber=0;
const cache=new Map();
function metric(value,label){return `<div class="metric"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function modelValue(m){return m.current?.status==='current_cached_indication'?m.current:m.close}
function reason(m){const c=m.close||{};if(m.data_status!=='ok')return m.data_status;if(!m.qualification?.[(modelValue(m)||{}).direction]?.passed)return 'Historical screen fails: '+(m.qualification?.[(modelValue(m)||{}).direction]?.reasons||['Unavailable']).join('; ');if(m.current?.eligible)return 'Eligible current cached indication';const base=c.state==='exit_pending'?'Exit pending':c.state==='cooldown'?'Cooldown':Math.abs(c.z)>=3.5?'Beyond adverse-stop band':Math.abs(c.z)<1.5?'Inside entry band':c.opportunity_bp<5?'Below 5bp to target':c.eligible?'Qualifies at last close':'No entry';return base+(m.current?.status!=='current_cached_indication'?' · '+(m.current?.status||'no current quotes').replaceAll('_',' '):'')}
function discovered(m,d){return (m.episodes||[]).find(e=>e.direction===d)}
function signalGroups(which){const result=[];for(const s of index.structures){const groups=new Map();for(const m of s.models){const seen=new Set();const admissions=Object.values(m.admissions||{}).filter(a=>['open','entry_pending','exit_pending','active'].includes(a.status)).sort((a,b)=>(b.status==='active')-(a.status==='active'));for(const admission of admissions){const d=admission.direction;if(seen.has(d))continue;seen.add(d);const ep=(m.episodes||[]).find(e=>e.signal_id===admission.signal_id);const obs=(m.observed||[]).find(o=>o.signal_id===admission.signal_id);const c=modelValue(m)||{};const current=m.current?.status==='current_cached_indication';const eligible=m.data_status==='ok'&&m.qualification?.[d]?.passed&&c.eligible&&c.direction===d&&(current||['open','entry_pending'].includes(c.state));const isNew=day(admission.first_qualified_at)===index.observed_at.slice(0,10)&&eligible;const use=which==='new'?isNew:!isNew;if(use){if(!groups.has(d))groups.set(d,{structure:s,d,models:[]});groups.get(d).models.push({m,c:which==='tracking'?(m.tracking||c):c,ep,obs,admission,basis:current?'cached indication':'last close'})}}}for(const g of groups.values())result.push(g)}return result.sort((a,b)=>Math.max(...b.models.map(v=>v.c.opportunity_bp||0))-Math.max(...a.models.map(v=>v.c.opportunity_bp||0)))}
const expanded={new:false,tracking:false};
function modelLines(g,fn){return g.models.map(v=>`<span class="model-line"><small>${names[v.m.model]}</small> ${fn(v)}</span>`).join('')}
function qualifiesNow(m,d){const c=modelValue(m)||{};return m.data_status==='ok'&&m.qualification?.[d]?.passed&&c.eligible&&c.direction===d&&(m.current?.status==='current_cached_indication'||['open','entry_pending'].includes(c.state))}
function agreement(g){return g.structure.models.filter(m=>qualifiesNow(m,g.d))}
function sample(v,d){return v.m.table_evidence?.[$('signal-period').value]?.[d===1?'long_quote':'short_quote']||{}}
function weakest(g,key){const values=g.models.map(v=>key==='opportunity'?v.c.opportunity_bp:sample(v,g.d)[key]);return values.every(Number.isFinite)?Math.min(...values):-Infinity}
function filteredGroups(which){const enabled=['method-mr','method-co','method-pca'].filter(id=>$(id).checked).map(id=>$(id).value),ccy=$('signal-currency').value;let groups=signalGroups(which).map(g=>({...g,models:g.models.filter(v=>enabled.includes(v.m.model))})).filter(g=>g.models.length&&(ccy==='all'||g.structure.ccys.includes(ccy))&&($('signal-focus').value!=='agreement'||agreement(g).length>=2));const mode=$('signal-sort').value;groups.sort((a,b)=>{let delta=mode==='agreement'?agreement(b).length-agreement(a).length:weakest(b,mode==='hit'?'win_rate':mode==='mean'?'gross_mean_bp':'opportunity')-weakest(a,mode==='hit'?'win_rate':mode==='mean'?'gross_mean_bp':'opportunity');if(Number.isFinite(delta)&&delta!==0)return delta;if(mode!=='agreement'){if(weakest(a,mode==='hit'?'win_rate':mode==='mean'?'gross_mean_bp':'opportunity')===-Infinity&&weakest(b,mode==='hit'?'win_rate':mode==='mean'?'gross_mean_bp':'opportunity')!==-Infinity)return 1;if(weakest(b,mode==='hit'?'win_rate':mode==='mean'?'gross_mean_bp':'opportunity')===-Infinity&&weakest(a,mode==='hit'?'win_rate':mode==='mean'?'gross_mean_bp':'opportunity')!==-Infinity)return -1;}const av=weakest(a,'gross_mean_bp'),bv=weakest(b,'gross_mean_bp');if(av!==bv)return av>bv?-1:1;return a.structure.name.localeCompare(b.structure.name)});return groups}
function renderSignals(which){const all=signalGroups(which),groups=filteredGroups(which),visible=expanded[which]?groups:groups.slice(0,10);$(which==='new'?'new-count':'tracking-count').textContent=`${groups.length} matching / ${all.length} groups${groups.length>10?' · showing '+visible.length:''}`;const container=$(which==='new'?'new-table':'tracking-table'),more=$(which+'-more');more.hidden=groups.length<=10;more.textContent=expanded[which]?'Show first 10':'Show all '+groups.length+' matching signals';if(!groups.length){container.innerHTML=`<p class="empty">${all.length?'No signals match these filters. Change methods, currency or agreement.':which==='new'?'No new qualified discoveries in this saved scan.':'No other active admitted signals in this scan.'}</p>`;height();return}
 const rows=visible.map(g=>{const agree=agreement(g),opposed=g.structure.models.filter(m=>qualifiesNow(m,-g.d));const badges=agree.length>=2?`<span class="agreement-badge" title="All qualifying methods: ${agree.map(m=>names[m.model]).join(', ')}">${agree.length} agree · ${agree.map(m=>names[m.model]).join(' / ')}</span>`:'';const exceptions=g.models.some(v=>v.m.data_status!=='ok'||!v.m.qualification?.[g.d]?.passed)?'<span class="opposition">Review tracking alert</span>':'';const quoteBadge=g.models.some(v=>v.basis==='cached indication')?'<span class="quote-badge">Current cache</span>':'';const link=`<a class="structure-link" href="#structure/${encodeURIComponent(g.structure.structure_id)}">${esc(g.structure.name)}</a>${badges}${opposed.length?'<span class="opposition">Opposing qualified view: '+opposed.map(m=>names[m.model]).join(' / ')+'</span>':''}${quoteBadge}${exceptions}`;
 const values=[link,directionCell(g.d,g.structure),quoteCell(g),g.models.map(v=>`<span class="method-label">${names[v.m.model]}</span>`).join(''),modelLines(g,v=>`${fmt(v.c.opportunity_bp,1)}bp`),modelLines(g,v=>{const e=sample(v,g.d);return `${pct(e.win_rate)} <span class="sample-count">n=${e.trades??0}</span>`}),modelLines(g,v=>{const e=sample(v,g.d);return `<span class="${e.gross_mean_bp<0?'negative':''}">${Number.isFinite(e.gross_mean_bp)?fmt(e.gross_mean_bp,1)+'bp':'—'}</span>`})];if(which==='tracking')values.push(modelLines(g,v=>v.obs?`${fmt(v.m.tracking?.gross_indication_change_bp,1)}bp observed`:`${fmt(v.m.close?.open_gross_bp,1)}bp simulated`));return `<tr class="${agree.length>=2?'agreement-row':''}">${values.map(v=>`<td>${v}</td>`).join('')}</tr>`});const headers=['Structure','Trade','Level · bp','Model','To target','Hit rate · n','Avg gross'];if(which==='tracking')headers.push('Mark change');container.innerHTML=`<table class="signal-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;height()}
function saveFilters(){try{sessionStorage.setItem('rv-signal-filters',JSON.stringify(Object.fromEntries(['method-mr','method-co','method-pca','signal-currency','signal-focus','signal-period','signal-sort'].map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]))))}catch{}}
function refreshSignals(){expanded.new=false;expanded.tracking=false;saveFilters();renderSignals('new');renderSignals('tracking')}
function initFilters(){const ccys=[...new Set(index.structures.flatMap(s=>s.ccys))].sort();$('signal-currency').innerHTML='<option value="all">All currencies</option>'+ccys.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');try{const saved=JSON.parse(sessionStorage.getItem('rv-signal-filters')||'{}');for(const [id,val] of Object.entries(saved)){const el=$(id);if(!el)continue;if(el.type==='checkbox')el.checked=!!val;else if([...el.options].some(o=>o.value===val))el.value=val}}catch{}for(const id of ['method-mr','method-co','method-pca','signal-currency','signal-focus','signal-period','signal-sort'])$(id).addEventListener('change',refreshSignals);$('pca-only').addEventListener('click',()=>{$('method-mr').checked=false;$('method-co').checked=false;$('method-pca').checked=true;refreshSignals()});$('reset-filters').addEventListener('click',()=>{for(const id of ['method-mr','method-co','method-pca'])$(id).checked=true;$('signal-currency').value='all';$('signal-focus').value='all';$('signal-period').value='since_2022';$('signal-sort').value='agreement';refreshSignals()});for(const which of ['new','tracking'])$(which+'-more').addEventListener('click',()=>{expanded[which]=!expanded[which];renderSignals(which)})}
function search(){const query=$('structure-search').value.trim();const box=$('search-results');box.hidden=!query;if(!query)return;const terms=query.toLowerCase().split(/\s+/).map(norm);const found=index.structures.filter(s=>{const hay=norm(s.name+' '+s.family+' '+s.ccys.join(' ')+' '+s.name.replaceAll('ESTR','EUR'));return terms.every(t=>hay.includes(t))});box.innerHTML=found.length?found.map(s=>`<a class="search-result" href="#structure/${encodeURIComponent(s.structure_id)}"><strong>${esc(s.name)}</strong><small>${esc(s.family.replaceAll('_',' '))} · ${s.models.filter(m=>m.data_status==='ok').length}/${s.models.length} models available</small></a>`).join(''):'<p class="empty">No structure matches. Try currency and tenors, for example AUD 3s5s10s.</p>'}
function chart(dates,series,labels){if(!dates?.length||!series[0]?.length)return '<p class="muted">Chart unavailable.</p>';const all=series.flat().filter(Number.isFinite);if(!all.length)return '<p class="muted">Chart unavailable.</p>';let lo=Math.min(...all),hi=Math.max(...all);const pad=(hi-lo)*.08||1;lo-=pad;hi+=pad;const W=700,H=240,L=57,R=18,T=18,B=30;const x=i=>L+i*(W-L-R)/Math.max(dates.length-1,1),y=v=>T+(hi-v)*(H-T-B)/(hi-lo),colors=['#175d49','#bf8a36'];let svg=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(labels.join(' and '))}">`;for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#e4e9e3"/><text x="4" y="${y(v)+4}">${fmt(v,1)}</text>`}series.forEach((a,j)=>{svg+=`<polyline fill="none" stroke="${colors[j]}" stroke-width="1.7" points="${a.map((v,i)=>`${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ')}"/>`});svg+=`<text x="${L}" y="${H-6}">${esc(dates[0])}</text><text x="${W-R}" y="${H-6}" text-anchor="end">${esc(dates.at(-1))}</text></svg>`;return svg+`<p class="legend">${labels.map((l,i)=>`<span style="color:${colors[i]}">● ${esc(l)}</span>`).join(' &nbsp; ')}</p>`}
function evidence(){const m=selected.models.find(m=>m.model===selectedModel),period=$('period').value,dir=$('evidence-direction').value,e=m.evidence?.[period]?.[dir];if(!e){$('evidence').innerHTML='<p>No estimable evidence.</p>';return}$('evidence').innerHTML=`<div class="kv">${[[e.trades,'Completed trades'],[Number.isFinite(e.win_rate)?fmt(e.win_rate*100,1)+'%':'—','Win rate'],[fmt(e.gross_mean_bp)+'bp','Mean gross outcome'],[fmt(e.gross_median_bp)+'bp','Median gross outcome'],[fmt(e.worst_trade_bp)+'bp','Worst trade'],[fmt(e.mean_mae_bp)+'bp','Mean adverse excursion'],[fmt(e.mean_hold_days,1)+' days','Mean holding time'],[fmt(e.mean_without_best_trade_bp)+'bp','Mean excluding best trade']].map(([v,l])=>`<div><strong>${esc(v)}</strong><span>${l}</span></div>`).join('')}</div><p class="muted">Entry-date cohorts; completed trades only. ${e.mark_gap_episodes} trades had a mark gap over five calendar days. Full-strategy maximum drawdown: ${fmt(m.max_drawdown_bp)}bp (includes open daily marks; not filtered by these controls).</p>`}
function renderModel(model){selectedModel=model;for(const b of $('model-tabs').children){b.classList.toggle('active',b.dataset.model===model);b.setAttribute('aria-pressed',String(b.dataset.model===model))}const m=selected.models.find(x=>x.model===model),c=modelValue(m)||{},diag=m.diagnostic_chart,eq=m.equity_chart;
 if(!m.evidence){$('model-detail').innerHTML=`<p class="notice">${esc(m.data_status)}</p>`;return}
 const q=m.qualification?.[c.direction];const qualificationText=q?`Historical screen: ${q.passed?'PASS':'FAIL'} · ${q.full_trades} full-history trades / ${q.recent_trades} since 2022 / ${q.direction_trades} in this direction. Mean gross bp: ${fmt(q.full_mean_bp)} full / ${fmt(q.recent_mean_bp)} since 2022 / ${fmt(q.direction_mean_bp)} in this direction. ${q.reasons.join('; ')}`:'Historical evidence unavailable';
 const exposures=Object.entries(selected.quote_exposure).map(([k,w])=>`${fmt(w,2)} × ${k}`).join(' + ');
 $('model-detail').innerHTML=`<section class="panel"><h3>${names[model]} · ${direction(c.direction)}</h3><p class="trade-legs">${esc(trade(c.direction,selected).detail)}</p><p>${esc(reason(m))}</p><p class="notice">${esc(qualificationText)}</p><div class="kv">${[[fmt(c.quote_bp),'Package quote, bp'],[fmt(c.fair_bp),'Fair value, bp'],[fmt(c.target_bp),'Exit target, bp'],[fmt(c.stop_bp),'Adverse stop, bp']].map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('')}</div><p class="muted">Source close ${index.cutoff}; current cache status: ${esc(m.current?.status||'unavailable')}. ${m.current?.oldest_snapshot_at?'Acquired '+sg(m.current.oldest_snapshot_at)+' to '+sg(m.current.latest_snapshot_at)+'.':''} Model trigger: ${esc(m.close?.alert_date||'none')}; simulated entry: ${esc(m.close?.entry_date||'none')}.</p><details><summary>Package expression & source conventions</summary><p><code>${esc(exposures)}</code></p><p>Trade labels specify which fixed rates to pay and receive. Flies are quoted as 2×belly−short wing−long wing: receiving the belly benefits when this quote falls. Curves are longer tenor minus shorter tenor; cross-market quotes are the first displayed currency minus the second. Coefficients are approximate rate exposures, not trade notionals; fly belly exposure is twice each wing.</p><p>${esc(selected.exposure_note)} All forwards are calculated from spot histories. Cross-market quote order follows the expression above.</p><p>${m.keys.map((k,i)=>`${esc(k)}: ${esc(m.tickers[i])}`).join('<br>')}</p></details></section>
 <section class="panel"><h3>Gross reference backtest evidence</h3><p class="muted">Walk-forward starts ${esc(m.walkforward_start)} · ${m.observations} overlapping observations. Signal-date ≥5bp floor; historical next-close fills; no costs. This is the underlying strategy history used to assess qualification, not a backtest of a historically screened portfolio.</p><div class="controls"><label>Period <select id="period"><option value="full">Full history</option><option value="since_2022">Since 2022</option><option value="since_2025">Since 2025</option></select></label><label>Direction <select id="evidence-direction"><option value="combined">Both</option><option value="long_quote">${direction(1)}</option><option value="short_quote">${direction(-1)}</option></select></label></div><div id="evidence"></div><h3>Cumulative gross strategy result · bp</h3>${eq?chart(eq.dates,[eq.gross_bp],['Rolling backtest, gross bp']):''}</section>
 <section class="panel"><h3>Current-fit diagnostics</h3><p class="notice">${esc(diag?.note||'Unavailable')}</p><div class="chart-grid"><div><h3>Quote and fair value · bp</h3>${diag?chart(diag.dates,[diag.quote_bp,diag.fair_bp],['Quote','Latest-fit fair value']):''}</div><div><h3>Residual z-score</h3>${diag?chart(diag.dates,[diag.z],['Latest-fit z']):''}</div></div></section>
 <details class="panel"><summary>Research sensitivities & statistical diagnostics</summary><p>Research diagnostics date: ${index.research_observed_at?sg(index.research_observed_at):'Not recomputed for this daily scan'}. These do not determine signal inclusion.</p>${m.bootstrap?`<p>90% block-bootstrap interval on mean daily gross bp: ${fmt(m.bootstrap.lower,4)} to ${fmt(m.bootstrap.upper,4)}. p=${fmt(m.bootstrap.p,4)}; BY q=${fmt(m.bootstrap.by_q,4)}; ${m.bootstrap.draws} draws; ${m.bootstrap.total_comparisons} planned comparisons. Includes inactive days.</p>`:'<p>Research diagnostics unavailable in this daily output.</p>'}${table(['Specification','Completed trades','Mean gross bp','Win rate'],Object.entries(m.sensitivities||{}).map(([k,v])=>[esc(k.replaceAll('_',' ')),v.evidence.full.combined.trades,fmt(v.evidence.full.combined.gross_mean_bp),pct(v.evidence.full.combined.win_rate)]).concat(m.unfiltered_diagnostic?[['Unfiltered diagnostic (no 5bp floor)',m.unfiltered_diagnostic.evidence.full.combined.trades,fmt(m.unfiltered_diagnostic.evidence.full.combined.gross_mean_bp),pct(m.unfiltered_diagnostic.evidence.full.combined.win_rate)]]:[]))}<p>Exploratory evidence; no untouched holdout claimed.</p></details>
 <details class="panel"><summary>Persistent model episode history (${m.timeline?.length||0})</summary><p>First observed is when this monitor recorded the episode, not a historical trade execution. Imported historical episodes retain their actual model trigger dates.</p><div class="timeline">${table(['Model trigger','First observed','Direction','Lifecycle'],[...(m.timeline||[])].reverse().map(e=>[esc(e.model_signal_date),sg(e.first_observed_at),direction(e.direction),esc(e.status)]))}</div></details>
 <details class="panel"><summary>Observed cached-indication history (${m.observed_history?.length||0})</summary><p>Changes from the first observed cached indication are not executed P&amp;L.</p>${(m.observed_history||[]).map(o=>`<p>${sg(o.first_observed_at)} · ${direction(o.direction)} · ${esc(o.status)} · first quote ${fmt(o.first_quote_bp)}bp${o.exit_reason?' · '+esc(o.exit_reason):''}</p>${table(['Observed','Quote bp','Gross indication change bp'],(o.marks||[]).map(v=>[sg(v.observed_at),fmt(v.quote_bp),fmt(v.gross_indication_change_bp)]))}`).join('')||'<p>No current cached indication has been recorded for this model.</p>'}</details>
 <details class="panel"><summary>Completed historical trades (${m.trades?.length||0})</summary><div class="timeline">${table(['Signal','Entry','Exit','Direction','Gross bp','MAE bp','Days','Exit reason'],[...(m.trades||[])].reverse().map(t=>[t.signal_date,t.entry_date,t.exit_date,direction(t.direction),fmt(t.gross_bp),fmt(t.mae_bp),t.hold_days,esc(t.exit_reason)]))}</div></details>`;
 $('period').addEventListener('change',evidence);$('evidence-direction').addEventListener('change',evidence);evidence();height();}
async function route(){const sequence=++requestNumber;const id=location.hash.startsWith('#structure/')?decodeURIComponent(location.hash.slice(11)):null;$('review').hidden=!id;$('overview').hidden=!!id;$('search-results').hidden=true;if(!id){height();return}try{let s=cache.get(id);if(!s){const response=await fetch('structures/'+encodeURIComponent(id)+'.json',{cache:'no-store'});if(!response.ok)throw Error('This structure could not be loaded.');s=await response.json();cache.set(id,s)}if(sequence!==requestNumber)return;selected=s;$('review-title').textContent=s.name;$('expression').textContent=s.family.replaceAll('_',' ')+' · '+s.models.length+' models · '+s.ccys.join(' / ');$('model-note').textContent='Compare each model separately. Model agreement is not an independent trade count; targets and performance are never averaged. '+(s.models.some(m=>m.current?.status==='current_cached_indication')?'Cached indications are shown where available.':'These readings use the last completed close; matching current snapshots are unavailable.');$('comparison').innerHTML=table(['Model','Quote bp','Fair bp','z','Gross bp to target','Direction','Status'],s.models.map(m=>{const c=modelValue(m)||{};return [names[m.model],fmt(c.quote_bp),fmt(c.fair_bp),fmt(c.z),fmt(c.opportunity_bp),directionCell(c.direction,s),`<span class="model-status">${esc(reason(m))}</span>`]}));$('model-tabs').replaceChildren();for(const m of s.models){const b=document.createElement('button');b.type='button';b.dataset.model=m.model;b.textContent=names[m.model];b.addEventListener('click',()=>renderModel(m.model));$('model-tabs').append(b)}renderModel(s.models.find(m=>m.data_status==='ok')?.model||s.models[0].model);window.scrollTo(0,0)}catch(e){$('load-error').hidden=false;$('load-error').textContent=e.message;}}
function height(){if(parent!==window)parent.postMessage({type:'rv-height',height:document.documentElement.scrollHeight},location.origin)}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#structure/"]');if(a&&parent!==window){e.preventDefault();parent.postMessage({type:'rv-structure',id:decodeURIComponent(a.hash.slice(11))},location.origin)}});
$('back').addEventListener('click',()=>{if(parent!==window)parent.postMessage({type:'rv-structure',id:null},location.origin);else location.hash=''});
$('structure-search').addEventListener('input',search);window.addEventListener('hashchange',route);document.addEventListener('toggle',height,true);window.addEventListener('resize',height);
fetch('index.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Saved scan unavailable');return r.json()}).then(data=>{index=data;const current=data.structures.flatMap(s=>s.models).filter(m=>m.current?.status==='current_cached_indication').length;$('run-meta').textContent='Scan '+sg(data.observed_at)+' · Completed close '+data.cutoff+' · v'+data.version+' · '+data.mode;$('coverage').innerHTML=metric(data.summary.structures,'structures')+metric(data.summary.evaluated+'/'+data.summary.models,'models evaluated')+metric(data.summary.held,'held models')+metric(current,'models with current quotes');$('freshness').textContent=current?'Current cached indications are available for '+current+' models. Other models retain their dated close readings. Cache timestamps are acquisition times, not guaranteed exchange times.':'No matching current spot snapshots in this cache. New today shows qualifying last-close discoveries, not live entry triggers. Refresh matching quotes before acting; no previous close is represented as a live quote.';$('new-note').textContent='Default order: same-direction model agreement, then the lowest displayed average gross outcome. Showing 10 at a time; filters change the view, not the qualification rules. Trigger dates, z-scores and model lifecycle are in each review.';$('coverage-detail').innerHTML='<p>Missing or stale inputs hold affected models; search still includes every structure.</p>'+table(['Ticker','Last cached close','Status'],data.held_sources.map(r=>[esc(r.ticker),esc(r.last||'none'),esc(r.status)]))+'<p>USD–EUR pairings use ESTR OIS. PCA applies only to spot shapes.</p>';initFilters();renderSignals('new');renderSignals('tracking');route()}).catch(e=>{$('load-error').hidden=false;$('load-error').textContent=e.message;$('run-meta').textContent='Unable to load the saved scan; this is not a zero-signal result.';height()});
